### ISSUE TITLE
How does the curly-brace expansion work?

### ISSUE THREAD

**Issue by zeke** [maxogden/nugget#13]
This is in the docs:

![multiple](https://cloud.githubusercontent.com/assets/2289/16661993/6dcf8578-442a-11e6-9985-a1f32a98466f.png)

Is there a name for this `{25..26}`  syntax?

What piece of code is interpreting this as a range of URLs?

**Comment by mafintosh** [comment]
bash expands the `{...}` syntax into multiple arguments. try running `echo foo{1..5}` fx

**Comment by zeke** [comment]
😎
