### ISSUE TITLE
Proxy option

### ISSUE THREAD

**Issue by ThomasCrvsr** [maxogden/nugget#8]
While installing `electron-prebuilt`, I had an error due to a proxy. Would it be possible to add more options to nugget ? Like `proxy` and `strictSSL` ?

**Comment by squirmy** [comment]
+1

**Comment by mafintosh** [comment]
Sounds like a good idea. If anyone is interested in sending a PR for this it would be appreciated

**Comment by ThomasCrvsr** [comment]
I could work on this tonight :)

**Comment by mafintosh** [comment]
Fixed in #10 by @ThomasCrvsr
